ir_cmd_uart:
  ros__parameters:
    set_params: true                    #enable writing of params. If false, the current parameters are simply printed.
    set_shutter: true                   #set auto shutter parameters
    set_fps: true                       #set fps parameter
    set_filter: true                    #set filter parameters / algorithm parameters
    save_params: true                   #save shutter config
    uart_data: "/dev/ttyHS1"            #The UART peripherial (/dev/ttyUSB0 for uart-usb adapter)
    baudrate: 115200                    #baudrate for communication channel
    auto_ffc_shutter: 0                 #auto shutter status
    image_detail_enhance_level: 0
    fps: 30                             #30 or 60 only
    image_noise_reduction_level: 0
    time_noise_reduction_level: 0
    space_noise_reduction_level: 100
    edge_enhance_level: 0
    image_scene_mode: 0


